Start from the dataset kickstarter-14-04, take out the unnecessary columsn that I don't know why are there:

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import nltk
from nltk.corpus import stopwords
import string 
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re 
from collections import Counter
import ast
import glob

In [2]:
campaigns = pd.read_csv('raw_kickstarter.csv', index_col=0)
campaigns

,url,title,description,pledged,usd_pledged,converted_pledged_amount,goal,currency
0,https://www.kickstarter.com/projects/thetruthb...,NaN,The PROBLEM: So much entertainment today pushe...,71123.0,71123.0,61607,48000.0,USD
1,https://www.kickstarter.com/projects/99625582/...,NaN,Millions of American college students have stu...,65318.0,65318.0,56579,61500.0,USD
2,https://www.kickstarter.com/projects/distortre...,Cartoon Network Alphabet Pins,Full A-Z Set I'm launching this set to show my...,462.0,462.0,400,8000.0,USD
3,https://www.kickstarter.com/projects/jordym/th...,The Balloon - a short film,"On a sleepy summer afternoon, we stared into t...",5137.0,5137.0,4449,15000.0,USD
4,https://www.kickstarter.com/projects/trans-mov...,NaN,48 hours of pledge matching! Amazing news! Two...,50640.0,50640.0,43865,50000.0,USD
...,...,...,...,...,...,...,...,...
8390,https://www.kickstarter.com/projects/zerwcolla...,ZerwCollab: Your AI-Powered App Builder in Sec...,🚀 What If You Could Launch a Website or App… U...,2128.0,2128.0,1823,35900.0,USD
8391,https://www.kickstarter.com/projects/jacobzirk...,VFX Oasis: Free VFX Assets and Footage,What is VFX Oasis? VFX Oasis is an industry fo...,580.0,580.0,496,6000.0,USD
8392,https://www.kickstarter.com/projects/153189407...,Sharp X - Edge Gadget,Kickstarter Project Story – USA-Market Sharpen...,857.0,857.0,734,7800.0,USD
8393,https://www.kickstarter.com/projects/diyengine...,Steady Shot Bot: Hyperlapse + Steadycam + Auto...,"Why As a hobbyist, I recently found myself wan...",6645.0,6645.0,5693,310000.0,USD
8394,https://www.kickstarter.com/projects/brilliant...,Covert Docking Headset | 008 | Hidden yet acce...,BRILLIANT BUDS INTRODUCES THE COVERT WIRELESS ...,3974.0,3974.0,3404,18000.0,USD

### as a very first step we add the categories to each project

In [3]:

folder_path = "Kickstarter_2026-03-12T03_20_26_556Z"

files = glob.glob(f"{folder_path}/*.csv")

print("Number of files found:", len(files))

dfs = []

for file in files:
    print("Loading:", file)
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)



url_to_category = {}
for _, row in df.iterrows():
    parsed = ast.literal_eval(row['category'])
    parent_name = parsed.get('parent_name') or parsed.get('name')
    url_parsed = ast.literal_eval(row['urls'])
    project_url = url_parsed['web']['project']
    url_to_category[project_url] = parent_name


campaigns['category'] = campaigns['url'].map(url_to_category)

print(f"Matched: {campaigns['category'].notna().sum()} / {len(campaigns)}")
print(campaigns['category'].value_counts())

Number of files found: 85
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter001.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter002.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter003.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter004.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter005.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter006.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter007.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter008.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter009.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter010.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter011.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter012.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter013.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter014.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter015.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter016.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter017.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter018.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter019.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter020.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter021.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter022.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter023.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter024.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter025.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter026.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter027.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter028.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter029.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter030.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter031.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter032.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter033.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter034.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter035.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter036.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter037.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter038.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter039.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter040.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter041.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter042.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter043.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter044.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter045.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter046.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter047.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter048.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter049.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter050.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter051.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter052.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter053.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter054.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter055.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter056.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter057.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter058.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter059.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter060.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter061.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter062.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter063.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter064.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter065.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter066.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter067.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter068.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter069.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter070.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter071.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter072.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter073.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter074.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter075.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter076.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter077.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter078.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter079.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter080.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter081.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter082.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter083.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter084.csv
Matched: 7354 / 7354
category
Film & Video    2011
Technology      1489
Games           1422
Music           1218
Publishing      1214
Name: count, dtype: int64

take out the unnecessary columns, add the reached one and classify as success or failure (maybe it's already in the initial dataset but honestly I don't remember)

In [4]:
campaigns['reached'] = (campaigns['pledged'] / campaigns['goal']) * 100

median_reached = campaigns['reached'].median()
campaigns['status'] = campaigns['reached'].apply(lambda x: 1 if x >= median_reached else 0)

In [5]:
campaigns

,url,title,description,pledged,usd_pledged,converted_pledged_amount,goal,currency,category,reached,status
0,https://www.kickstarter.com/projects/thetruthb...,NaN,The PROBLEM: So much entertainment today pushe...,71123.0,71123.0,61607,48000.0,USD,Film & Video,148.172917,1
1,https://www.kickstarter.com/projects/99625582/...,NaN,Millions of American college students have stu...,65318.0,65318.0,56579,61500.0,USD,Film & Video,106.208130,1
2,https://www.kickstarter.com/projects/distortre...,Cartoon Network Alphabet Pins,Full A-Z Set I'm launching this set to show my...,462.0,462.0,400,8000.0,USD,Film & Video,5.775000,0
3,https://www.kickstarter.com/projects/jordym/th...,The Balloon - a short film,"On a sleepy summer afternoon, we stared into t...",5137.0,5137.0,4449,15000.0,USD,Film & Video,34.246667,0
4,https://www.kickstarter.com/projects/trans-mov...,NaN,48 hours of pledge matching! Amazing news! Two...,50640.0,50640.0,43865,50000.0,USD,Film & Video,101.280000,0
...,...,...,...,...,...,...,...,...,...,...,...
8390,https://www.kickstarter.com/projects/zerwcolla...,ZerwCollab: Your AI-Powered App Builder in Sec...,🚀 What If You Could Launch a Website or App… U...,2128.0,2128.0,1823,35900.0,USD,Technology,5.927577,0
8391,https://www.kickstarter.com/projects/jacobzirk...,VFX Oasis: Free VFX Assets and Footage,What is VFX Oasis? VFX Oasis is an industry fo...,580.0,580.0,496,6000.0,USD,Technology,9.666667,0
8392,https://www.kickstarter.com/projects/153189407...,Sharp X - Edge Gadget,Kickstarter Project Story – USA-Market Sharpen...,857.0,857.0,734,7800.0,USD,Technology,10.987179,0
8393,https://www.kickstarter.com/projects/diyengine...,Steady Shot Bot: Hyperlapse + Steadycam + Auto...,"Why As a hobbyist, I recently found myself wan...",6645.0,6645.0,5693,310000.0,USD,Technology,2.143548,0
8394,https://www.kickstarter.com/projects/brilliant...,Covert Docking Headset | 008 | Hidden yet acce...,BRILLIANT BUDS INTRODUCES THE COVERT WIRELESS ...,3974.0,3974.0,3404,18000.0,USD,Technology,22.077778,0

Preprocessing: usual preprocessing stuff like lowercasing, taking out links, only keepin alpha numeric characters, tokenizing the words, and taking out the english stopwords, also took out the words that are less than 2 characters

In [6]:
def preprocess(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', ' ', text)
    text_p = "".join([char for char in text if char.isalnum() or char.isspace()])
    
    words = word_tokenize(text_p) 
    
    
    stop_words = stopwords.words('english')
    words = [w for w in words if w not in stop_words and len(w) > 2 and w.isalpha()]
    filtered_words = [word for word in words if word not in stop_words] 
    
    return filtered_words  

campaigns['description_processed'] = campaigns['description'].apply(preprocess)

How do we decide which stopwords to include beside the 'normal' stopwords? We also want to include words that are very generic, not informative at all and coudl potentially appear in any kind of campaign, regardless of the topics in it (some examples could be the words 'kickstarter', campaign, etc etc)
Initially I thought TF-IDF would make sense but it doesn't actually, because TF-IDF both depends on how frequent a word is in each document and how frequent are documents that contain that words in the whole set of documents. (also you cannot average the TF-IDF of a word and pick the ones with lowest value because a rare word, which we wanna keep, could end up having a low TF-IDF value if it appears in few documents but many time in those few documents)
So potentially we can just use document frequency, meaning if the word appears in > alpha% of documents, we count it as a stopword?

Also quick sidenote: Other methods like BytePair encoding, WordPiece or SentencePiece are not really useful here because they look at subwords, and for example if we get 'kickstarter' and split it into kick and starter, then we might consider to keep kick because it makes sense with sport but we might not have any document where the word is present for real

This below just basically gives a counter of the document frequency of each token in our whole corpus of all the descriptions

We apply lemmatization (I think probably better than stemming since it returns the lemma version of the word, instead of just cutting the ending of the word). We apply it now, before taking out the domain specific stopwords, because otherwise we could end up having to account for different versions of the same stopword (example: project vs projects)

In [7]:
lemmatizer = WordNetLemmatizer()

campaigns['lemmatized'] = campaigns['description_processed'].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words])

In [8]:
initial_vocab = set(token for doc in campaigns['lemmatized'] for token in doc)
print(f"lenght of the initial vocabulary: {len(initial_vocab)}")

lenght of the initial vocabulary: 111122

In [9]:
docs = campaigns['lemmatized']
N = len(docs)

df_counter = Counter()

for doc in docs:
    df_counter.update(set(doc))

df_table = pd.DataFrame({
    'word': list(df_counter.keys()),
    'doc_freq': list(df_counter.values())
})

df_table['doc_freq_ratio'] = df_table['doc_freq'] / N
df_table = df_table.sort_values('doc_freq_ratio', ascending=False)

In [10]:
print(f"total number of tokens is: {len(df_table)}")
df_table

total number of tokens is: 111122

                 word  doc_freq  doc_freq_ratio
115               one      5194        0.706282
13               make      5190        0.705738
388              time      5127        0.697172
16               help      4925        0.669704
237           project      4743        0.644955
...               ...       ...             ...
111111        eyework         1        0.000136
111110        mussing         1        0.000136
111109            dbu         1        0.000136
111108  noncontinuous         1        0.000136
111107       adatsmux         1        0.000136

[111122 rows x 3 columns]

Now the only method and the one that made most sense to me to take out too common words is basically just defining a threshold and see which words are too rare (like if it appears only 2-3 times in the whole dataset) or too much (in this case too much can be like appearing in more than 40-60% of the descriptions), you can try different values of the two initial thresholds (the one I saw looks the best would be 0.0005 for the low and 0.55 for the high)

In [11]:
min_doc_count = 5
min_ratio = min_doc_count / N
top_n_words = 100


top_words_preview = (
    df_table
    .sort_values('doc_freq_ratio', ascending=False)
    .head(top_n_words)
)

print(df_table[df_table['doc_freq_ratio'] <= min_ratio])
top_words_preview

                 word  doc_freq  doc_freq_ratio
27874           única         5        0.000680
31613         avenged         5        0.000680
21863            homo         5        0.000680
42164          regent         5        0.000680
42160         detract         5        0.000680
...               ...       ...             ...
111111        eyework         1        0.000136
111110        mussing         1        0.000136
111109            dbu         1        0.000136
111108  noncontinuous         1        0.000136
111107       adatsmux         1        0.000136

[88937 rows x 3 columns]

         word  doc_freq  doc_freq_ratio
115       one      5194        0.706282
13       make      5190        0.705738
388      time      5127        0.697172
16       help      4925        0.669704
237   project      4743        0.644955
...       ...       ...             ...
822    please      2158        0.293446
2895     hope      2151        0.292494
53       film      2131        0.289774
318      used      2122        0.288550
939     small      2099        0.285423

[100 rows x 3 columns]

In [12]:
vocab = set(
    df_table['word']
)
print(f"length of initial vocabulary is {len(vocab)}")

rare_words = set(df_table['word'][df_table['doc_freq_ratio'] <= min_ratio] )


common_words = set(top_words_preview["word"])
vocab = vocab - common_words - rare_words
print(f"there are {len(common_words)} common words")
print(f"there are {len(rare_words)} rare words")
print(f"Removed {len(rare_words) + len(common_words)} words from vocab")
print(f"the vocabulary size now after having took out the general stopwords (not category specific) is {len(vocab)} tokens")
vocab

length of initial vocabulary is 111122
there are 100 common words
there are 88937 rare words
Removed 89037 words from vocab
the vocabulary size now after having took out the general stopwords (not category specific) is 22085 tokens

{'succulent',
 'submit',
 'brochure',
 'yielded',
 'suburb',
 'florentine',
 'strength',
 'outside',
 'fad',
 'type',
 'anguish',
 'simplifies',
 'crackling',
 'vic',
 'sweetwater',
 'reducing',
 'doable',
 'sustaining',
 'explorando',
 'bohemian',
 'shelley',
 'astral',
 'perilous',
 'complex',
 'meticulously',
 'stitcher',
 'thermoplastic',
 'better',
 'synth',
 'tidbit',
 'weaken',
 'necessity',
 'screwdriver',
 'bookworm',
 'hardware',
 'unexpected',
 'coat',
 'unconfirmed',
 'reinvention',
 'loss',
 'journalist',
 'projectile',
 'chuckle',
 'congested',
 'optimize',
 'advert',
 'onslaught',
 'neo',
 'shoutout',
 'havoc',
 'outperforms',
 'stimulates',
 'architecture',
 'culminated',
 'whirlwind',
 'ascended',
 'photography',
 'browne',
 'perfume',
 'horrific',
 'punched',
 'entity',
 'lived',
 'garden',
 'mecha',
 'misstep',
 'davenport',
 'whats',
 'edits',
 'coexecutive',
 'yellowing',
 'alley',
 'lavender',
 'forgive',
 'reawaken',
 'rebellion',
 'obscure',
 'helium',
 'mattel',
 'shooting',
 'calamity',
 'kingston',
 'licensing',
 'employ',
 'favorable',
 'theyve',
 'unearthed',
 'recounting',
 'feelgood',
 'reshaping',
 'shortsfest',
 'thea',
 'langley',
 'meantime',
 'accepted',
 'hardworking',
 'shaky',
 'autograph',
 'boldness',
 'wile',
 'buying',
 'privacy',
 'syllable',
 'cocktail',
 'absorbs',
 'airing',
 'posible',
 'violent',
 'travel',
 'differentiator',
 'dreamed',
 'incorporation',
 'interspersed',
 'fourpart',
 'ferguson',
 'modeled',
 'allstars',
 'gen',
 'worldly',
 'compact',
 'occupational',
 'stop',
 'leica',
 'remix',
 'appearance',
 'encapsulates',
 'inbetween',
 'fifteenth',
 'knapp',
 'preset',
 'lavish',
 'alien',
 'solder',
 'album',
 'dictate',
 'adair',
 'eel',
 'ive',
 'morbid',
 'meringue',
 'legitimate',
 'gareth',
 'adorned',
 'skim',
 'substrate',
 'whimsical',
 'anticipated',
 'idiosyncratic',
 'nasa',
 'watson',
 'purchaser',
 'melbourne',
 'stepbased',
 'cook',
 'justin',
 'número',
 'lock',
 'veritable',
 'formulating',
 'swim',
 'inversion',
 'spire',
 'who',
 'hailed',
 'racy',
 'faust',
 'manually',
 'sherpa',
 'bathe',
 'cocoa',
 'threedimensional',
 'alike',
 'waterfall',
 'connoisseur',
 'rhodes',
 'shapeshifter',
 'nicholas',
 'paperback',
 'nonpartisan',
 'beeswax',
 'paltz',
 'tldr',
 'persuade',
 'convinced',
 'selfappointed',
 'primary',
 'simplifying',
 'crack',
 'compressing',
 'browser',
 'apology',
 'revolving',
 'hexagonal',
 'mama',
 'modality',
 'indebted',
 'mccoy',
 'left',
 'finn',
 'distributing',
 'sunset',
 'emergent',
 'shuts',
 'stating',
 'reinvented',
 'carried',
 'homing',
 'bullied',
 'conservative',
 'dominic',
 'highefficiency',
 'rampant',
 'landed',
 'distanced',
 'yankovic',
 'embarrassing',
 'darin',
 'twitch',
 'jennings',
 'weaver',
 'sideshow',
 'host',
 'suburbia',
 'adorable',
 'chiefly',
 'carson',
 'homer',
 'outlasting',
 'traumatic',
 'sybil',
 'bookseller',
 'traffic',
 'decadence',
 'wisconsin',
 'master',
 'preceding',
 'pesticide',
 'cinematically',
 'remarked',
 'doomscrolling',
 'looking',
 'anodizing',
 'communitybased',
 'josephine',
 'factoring',
 'rubberized',
 'aiden',
 'uncle',
 'leaf',
 'milling',
 'beatles',
 'inevitability',
 'processor',
 'preserved',
 'dop',
 'hearthstone',
 'redesigned',
 'jose',
 'founder',
 'glen',
 'battlemaps',
 'seychelles',
 'heck',
 'sucker',
 'paramedic',
 'alyse',
 'mindbending',
 'smattering',
 'domain',
 'kjelsberg',
 'poem',
 'console',
 'freaking',
 'idaho',
 'educate',
 'coyote',
 'frontier',
 'bless',
 'alzheimers',
 'foilstamped',
 'balcony',
 'intricate',
 'nutritional',
 'eerie',
 'ripped',
 'particular',
 'arc',
 'succeeded',
 'absorbed',
 'jockey',
 'stared',
 'jrpg',
 'con',
 'closing',
 'postkickstarter',
 'although',
 'comparison',
 'humanos',
 'trademarked',
 'pivotal',
 'cannes',
 'vanilla',
 'liege',
 'kyles',
 'collector',
 'meteor',
 'reat',
 'splash',
 'maker',
 'logistically',
 'conveyed',
 'tuesday',
 'espacio',
 'princess',
 'grabbing',
 'cleanly',
 'attuned',
 'knowledgable',
 'fable',
 'decrease',
 'barrymore',
 'escalation',
 'stylized',
 'hurl',
 'structured',
 'taboo',
 'glyph',
 'shopify',
 'utopian',
 'lyon',
 'tweaking',
 'yummy',
 'kino',
 'rawlings',
 'overweight',
 'algae',
 'component',
 'mclaughlin',
 'asian',
 'roguelite',
 'sweater',
 'gatekeeping',
 'masculine',
 'exercise',
 'unshakable',
 'himalayan',
 'interior',
 'tragically',
 'random',
 'loosely',
 'ley',
 'splurge',
 'thumb',
 'inconsistent',
 'debra',
 'vii',
 'dell',
 'control',
 'rooftop',
 'wed',
 'dad',
 'drawer',
 'categorize',
 'revolutionizing',
 'thermostat',
 'indicates',
 'bradford',
 'lineup',
 'scratching',
 'kale',
 'assigning',
 'poverty',
 'plier',
 'exorcist',
 'kowalczuk',
 'velvet',
 'remit',
 'social',
 'aggression',
 'ominous',
 'nyt',
 'casting',
 'protesting',
 'derives',
 'unmasked',
 'manifested',
 'interviewer',
 'threepart',
 'marin',
 'pesky',
 'intuitive',
 'transported',
 'famine',
 'abound',
 'hydration',
 'dysfunctional',
 'indulgent',
 'displacement',
 'dreamer',
 'fue',
 'undergrowth',
 'largescale',
 'governance',
 'fastest',
 'rescue',
 'quality',
 'connects',
 'juice',
 'blew',
 'tribulation',
 'mature',
 'reunite',
 'adjustable',
 'mcrae',
 'replete',
 'pistol',
 'backroom',
 'brick',
 'strippeddown',
 'dealing',
 'volunteerrun',
 'threeweek',
 'wellversed',
 'sneaky',
 'actionadventure',
 'memorizing',
 'fullness',
 'appalled',
 'contact',
 'willard',
 'rew',
 'astronomer',
 'twoplayer',
 'lauren',
 'rumination',
 'juggling',
 'longerterm',
 'oneills',
 'positivity',
 'easygoing',
 'housed',
 'oversaw',
 'detecting',
 'movement',
 'command',
 'minion',
 'embedded',
 'gothic',
 'guilty',
 'preacher',
 'emblazoned',
 'wiping',
 'nprs',
 'artisan',
 'refurbished',
 'cutthroat',
 'slows',
 'collaborating',
 'rethink',
 'catharsis',
 'guarantee',
 'product',
 'trapping',
 'onthego',
 'noticed',
 'succumbed',
 'rigged',
 'deem',
 'communicates',
 'truthfully',
 'cambio',
 'medic',
 'liquid',
 'desafío',
 'viewpoint',
 'caters',
 'brooklyn',
 'fanbase',
 'minigames',
 'selected',
 'flimsy',
 'sandy',
 'vulnerability',
 'ascendant',
 'annotated',
 'topping',
 'nurse',
 'patentpending',
 'disclosure',
 'stressed',
 'ronaldo',
 'teaser',
 'equal',
 'jawdropping',
 'higgins',
 'goose',
 'rosary',
 'euphoria',
 'supersafe',
 'rehearsal',
 'inject',
 'biking',
 'lem',
 'forget',
 'empowered',
 'tan',
 'charge',
 'drowning',
 'voltage',
 'isnt',
 'surely',
 'lazer',
 'rectangle',
 'vapor',
 'far',
 'lodge',
 'buck',
 'biometrics',
 'ringside',
 'freelancer',
 'stein',
 'stark',
 'gang',
 'tcf',
 'seriousness',
 'sneaker',
 'iron',
 'key',
 'translated',
 'keppy',
 'supreme',
 'till',
 'hyperactive',
 'rubble',
 'obscura',
 'imdb',
 'banning',
 'typewriter',
 'ridden',
 'observation',
 'nicolas',
 'crumb',
 'whereby',
 'brannan',
 'substantially',
 'bleeding',
 'blogging',
 'upright',
 'release',
 'emblem',
 'bibliography',
 'demico',
 'soccer',
 'reflected',
 'rebrand',
 'grill',
 'firecracker',
 'enhance',
 'confirm',
 'darcy',
 'captivated',
 'imposter',
 'standardized',
 'gendered',
 'demolition',
 'desolate',
 'accusation',
 'ash',
 'ingredient',
 'steering',
 'de',
 'plumbing',
 'fastener',
 'insanely',
 'contradiction',
 'challenged',
 'genetically',
 'happy',
 'pc',
 'krauss',
 'hail',
 'contracting',
 'plural',
 'tcg',
 'gliding',
 'fantasia',
 'catfish',
 'outsourced',
 'folly',
 'fun',
 'escapism',
 'orchestral',
 'philosophy',
 'bachelor',
 'orcs',
 'hindalong',
 'whove',
 'image',
 'preparing',
 'passim',
 'restores',
 'consideration',
 'decisionmaking',
 'clung',
 'stalwart',
 'thunder',
 'intake',
 'geological',
 'brainstorm',
 'graham',
 'configured',
 'colorchanging',
 'aural',
 'severely',
 'tend',
 'casino',
 'filtered',
 'usernames',
 'roland',
 'jerusalem',
 'glow',
 'wild',
 'carolyn',
 'slow',
 'nashville',
 'leaning',
 'parrot',
 'duncan',
 'bitrate',
 'unpack',
 'culprit',
 'selects',
 'reinforcement',
 'musing',
 'pace',
 'subway',
 'victorious',
 'prototyped',
 'audio',
 'attraction',
 'base',
 'huge',
 'nigerian',
 'contraction',
 'beany',
 'hackable',
 'viewership',
 'harmoniously',
 'braided',
 'topic',
 'soc',
 'uncovering',
 'shower',
 'azure',
 'runnerup',
 'curated',
 'tomato',
 'fertile',
 'frontrow',
 'understanding',
 'getty',
 'rollback',
 'zealand',
 'expecting',
 'venerable',
 'five',
 'circulation',
 'cornucopia',
 'boost',
 'chainsaw',
 'incentivize',
 'blair',
 'ifwhen',
 'categorizes',
 'sullivan',
 'ingame',
 'boon',
 'vida',
 'warns',
 'internalized',
 'snazzy',
 'nephew',
 'soundtrack',
 'captive',
 'unidentified',
 'grandfather',
 'inhabit',
 'nutrient',
 'explosion',
 'strategy',
 'adaptability',
 'animal',
 'multiplied',
 'codesigner',
 'reversed',
 'playset',
 'flourished',
 'provoking',
 'anarchist',
 'brush',
 'button',
 'seeming',
 'enjoying',
 'cardbased',
 'holiness',
 'catering',
 'revitalize',
 'fundraise',
 'varying',
 'rudimentary',
 'richter',
 'recieve',
 'championed',
 'bush',
 'landing',
 'stabilized',
 'actorsactresses',
 'lawrence',
 'fruitful',
 'grail',
 'gemstone',
 'sen',
 'usually',
 'excellence',
 'curved',
 'smartest',
 'busca',
 'telling',
 'bona',
 'randy',
 'sanwa',
 'coauthored',
 'devotional',
 'balloon',
 'demographic',
 'identification',
 'potter',
 'acquainted',
 'portraying',
 'tommy',
 'roster',
 'evaluated',
 'airframe',
 'crouch',
 'larkins',
 'delicious',
 'takedown',
 'whisk',
 'rodgers',
 'shadow',
 'three',
 'sergio',
 'oneperson',
 'behemoth',
 'songua',
 'compensated',
 'butch',
 'using',
 'monica',
 'eduardo',
 'church',
 'grindhouse',
 'postproduction',
 'mejores',
 'radius',
 'wrapped',
 'esteem',
 'hurston',
 'comparative',
 'intaglio',
 'acn',
 'sanderson',
 'blond',
 'conspiracy',
 'paintbrush',
 'wooden',
 'socket',
 'serpentine',
 'conventional',
 'anki',
 'dispatched',
 'sale',
 'misconception',
 'boot',
 'abridged',
 'reiterate',
 'bitesized',
 'nuestra',
 'pulitzer',
 'playtests',
 'burglar',
 'steadiness',
 'harsh',
 'pulling',
 'humanmade',
 'almond',
 'internet',
 'mentioning',
 'distributes',
 'legal',
 'director',
 'blunder',
 'boomer',
 'burden',
 'esl',
 'cuddly',
 'ebike',
 'faye',
 'saul',
 'postapocalyptic',
 'neutral',
 'zoetrope',
 'toughest',
 'maze',
 'businessmen',
 'iterated',
 'ontranto',
 'assoc',
 'cathartic',
 'asheville',
 'erupted',
 'mud',
 'prepping',
 'unconditionally',
 'frail',
 'mem',
 'jan',
 'scrollable',
 'multimedia',
 'shirley',
 'asset',
 'halfhour',
 'tropical',
 'talkin',
 'tab',
 'euuk',
 'wingspan',
 'onesided',
 'livestreaming',
 'hoard',
 'denote',
 'percussionist',
 'persuasion',
 'annoying',
 'maternal',
 'merchant',
 'trading',
 'contract',
 'free',
 'gutter',
 'witcher',
 'wisely',
 'collide',
 'graveyard',
 'august',
 'criticism',
 'katrina',
 'bounce',
 'accelerate',
 'coast',
 'liberia',
 'oldest',
 'ironclad',
 'relentlessly',
 'chased',
 'wichita',
 'directing',
 'jigsaw',
 'terrence',
 'stained',
 'rhyming',
 'detect',
 'amusement',
 'disproportionate',
 'howtos',
 'troublesome',
 'enforces',
 'curator',
 'flexibility',
 'kindly',
 'satisfies',
 'brute',
 'evangelho',
 'corporate',
 'descriptive',
 'hindering',
 'mingling',
 'squeezing',
 'payroll',
 'sidewalk',
 'fostered',
 'modernizes',
 'applicable',
 'andy',
 'madison',
 'realmente',
 'attack',
 'promise',
 'octavia',
 'skyrocketed',
 'chunk',
 'multiplatform',
 'saving',
 'nearby',
 'conscientious',
 'lite',
 'newborn',
 'annapolis',
 'pity',
 'periodical',
 'fondly',
 'overcoming',
 'barebones',
 'uplifted',
 'instance',
 'musician',
 'chair',
 'maureen',
 'bottom',
 'sixyearold',
 'whether',
 'overtheair',
 'kevon',
 'marchapril',
 'ribbon',
 'survive',
 'rancher',
 'thereof',
 'diesel',
 'cooper',
 'hunting',
 'arcanum',
 'searchlight',
 'aligning',
 'maryland',
 'bitter',
 'ken',
 'lea',
 'concern',
 'distracted',
 'librarian',
 'hace',
 'replacing',
 'abducted',
 'week',
 'prestigious',
 'finetune',
 'coen',
 'summary',
 'muchneeded',
 'bianca',
 'sectional',
 'urgent',
 'dwarf',
 'colossus',
 'cocina',
 'rio',
 'robot',
 'octopus',
 'skype',
 'collected',
 'biometric',
 'lighthouse',
 'fungi',
 'submitted',
 'default',
 'bidder',
 'funk',
 'goodness',
 'commissioning',
 'uav',
 'greenish',
 'brit',
 'prominent',
 'casual',
 'visually',
 'forwardthinking',
 'trench',
 'sabine',
 'acknowledgement',
 'algunos',
 'flooring',
 'mallory',
 'spore',
 'tube',
 'arvr',
 'bubbly',
 'connector',
 'glenn',
 'falling',
 'kruger',
 'simultaneous',
 'fearlessly',
 'happens',
 'apex',
 'necessary',
 'fing',
 'miss',
 'finding',
 'greeted',
 ...}

### Now we work on the data specific category by category

In [13]:
# to actually take the overall common words out CAREFUL TO RUN 
campaigns['description_processed'] = campaigns['lemmatized'].apply(
    lambda doc: [w for w in doc if w in vocab]
)
campaigns = campaigns.drop(columns=['lemmatized'])

In [14]:
df = campaigns

In [15]:
df

,url,title,description,pledged,usd_pledged,converted_pledged_amount,goal,currency,category,reached,status,description_processed
0,https://www.kickstarter.com/projects/thetruthb...,NaN,The PROBLEM: So much entertainment today pushe...,71123.0,71123.0,61607,48000.0,USD,Film & Video,148.172917,1,"[problem, entertainment, today, push, unholy, ..."
1,https://www.kickstarter.com/projects/99625582/...,NaN,Millions of American college students have stu...,65318.0,65318.0,56579,61500.0,USD,Film & Video,106.208130,1,"[million, american, college, student, studied,..."
2,https://www.kickstarter.com/projects/distortre...,Cartoon Network Alphabet Pins,Full A-Z Set I'm launching this set to show my...,462.0,462.0,400,8000.0,USD,Film & Video,5.775000,0,"[launching, early, cartoon, network, started, ..."
3,https://www.kickstarter.com/projects/jordym/th...,The Balloon - a short film,"On a sleepy summer afternoon, we stared into t...",5137.0,5137.0,4449,15000.0,USD,Film & Video,34.246667,0,"[sleepy, summer, afternoon, stared, void, floa..."
4,https://www.kickstarter.com/projects/trans-mov...,NaN,48 hours of pledge matching! Amazing news! Two...,50640.0,50640.0,43865,50000.0,USD,Film & Video,101.280000,0,"[hour, pledge, matching, amazing, news, genero..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8390,https://www.kickstarter.com/projects/zerwcolla...,ZerwCollab: Your AI-Powered App Builder in Sec...,🚀 What If You Could Launch a Website or App… U...,2128.0,2128.0,1823,35900.0,USD,Technology,5.927577,0,"[launch, website, app, using, voice, imagine, ..."
8391,https://www.kickstarter.com/projects/jacobzirk...,VFX Oasis: Free VFX Assets and Footage,What is VFX Oasis? VFX Oasis is an industry fo...,580.0,580.0,496,6000.0,USD,Technology,9.666667,0,"[vfx, oasis, vfx, oasis, industry, focused, vi..."
8392,https://www.kickstarter.com/projects/153189407...,Sharp X - Edge Gadget,Kickstarter Project Story – USA-Market Sharpen...,857.0,857.0,734,7800.0,USD,Technology,10.987179,0,"[real, today, modern, especially, continues, l..."
8393,https://www.kickstarter.com/projects/diyengine...,Steady Shot Bot: Hyperlapse + Steadycam + Auto...,"Why As a hobbyist, I recently found myself wan...",6645.0,6645.0,5693,310000.0,USD,Technology,2.143548,0,"[hobbyist, recently, found, wanting, photograp..."
8394,https://www.kickstarter.com/projects/brilliant...,Covert Docking Headset | 008 | Hidden yet acce...,BRILLIANT BUDS INTRODUCES THE COVERT WIRELESS ...,3974.0,3974.0,3404,18000.0,USD,Technology,22.077778,0,"[brilliant, bud, introduces, covert, wireless,..."

#### 1. Identification of words appearing in more than 40% of documents

In [16]:

selected_categories = ['Technology', 'Games', 'Music', 'Publishing', 'Film & Video']
top_n_words = 50
category_high_freq_words = {}

for category_name in selected_categories:
    category_df = df[df["category"] == category_name].copy()
    docs = category_df["description_processed"]
    
    category_counter = Counter()
    for doc in docs:
        category_counter.update(set(doc))

    category_table = pd.DataFrame({
        "word": list(category_counter.keys()),
        "doc_freq": list(category_counter.values())
    })

    category_table["doc_freq_ratio"] = category_table["doc_freq"] / len(docs)
    high_freq_words = category_table.sort_values("doc_freq_ratio", ascending=False).head(top_n_words)

    category_high_freq_words[category_name] = high_freq_words
    print(f"\n{category_name}")
    display(high_freq_words)

category_high_freq_words

Technology

             word  doc_freq  doc_freq_ratio
196       product       854        0.573539
291      designed       802        0.538617
66          using       746        0.501007
71     technology       701        0.470786
317        system       672        0.451310
169          user       667        0.447952
177       control       618        0.415044
105        device       611        0.410343
285          easy       601        0.403627
117         power       597        0.400940
11    development       580        0.389523
264         build       571        0.383479
605        better       570        0.382807
310          tool       548        0.368032
276        allows       539        0.361988
296           app       533        0.357958
392        simple       529        0.355272
150     prototype       524        0.351914
931         start       521        0.349899
100         built       514        0.345198
87          offer       509        0.341840
648       quality       505        0.339154
306       process       504        0.338482
1288        ready       483        0.324379
221       provide       483        0.324379
496          high       483        0.324379
341        change       480        0.322364
141      solution       479        0.321692
530          idea       478        0.321021
1102      company       477        0.320349
208         youre       476        0.319678
666        backer       472        0.316991
275       content       469        0.314976
437          free       463        0.310947
297      platform       458        0.307589
179        access       455        0.305574
30         future       455        0.305574
1133       easily       449        0.301545
345         based       448        0.300873
408       perfect       438        0.294157
330       created       436        0.292814
51       possible       435        0.292142
468      software       432        0.290128
448       already       430        0.288784
881      building       429        0.288113
321        market       423        0.284083
2053      browser       423        0.284083
975          hand       421        0.282740
1162      problem       421        0.282740
159         thats       412        0.276696

Games

             word  doc_freq  doc_freq_ratio
81           game      1199        0.843179
1101       player       864        0.607595
285        backer       667        0.469058
379     character       649        0.456399
438       stretch       645        0.453586
629           end       630        0.443038
1190          fun       624        0.438819
658           add       617        0.433896
648      shipping       613        0.431083
458        pledge       608        0.427567
690      designed       595        0.418425
969        system       583        0.409986
257    additional       566        0.398031
48          youre       562        0.395218
234         using       558        0.392405
510          card       557        0.391702
995         based       538        0.378340
562         final       533        0.374824
2012        build       531        0.373418
443      complete       525        0.369198
193         start       524        0.368495
95        playing       523        0.367792
1721      special       519        0.364979
1067      content       512        0.360056
118         order       507        0.356540
902      gameplay       507        0.356540
53         always       502        0.353024
359          idea       498        0.350211
284        change       494        0.347398
726        choose       491        0.345288
526          book       490        0.344585
1348         free       487        0.342475
0         already       482        0.338959
951      creating       480        0.337553
340       product       479        0.336850
441       version       477        0.335443
1346         tier       475        0.334037
502     adventure       473        0.332630
755   development       472        0.331927
587    everything       472        0.331927
125       include       468        0.329114
1685     everyone       467        0.328411
795      includes       465        0.327004
720       created       462        0.324895
657      possible       460        0.323488
912          last       460        0.323488
862       digital       457        0.321378
209           box       456        0.320675
61           join       455        0.319972
282      original       451        0.317159

Music

           word  doc_freq  doc_freq_ratio
309       album       895        0.734811
92         song       880        0.722496
268   recording       801        0.657635
37       record       745        0.611658
7        studio       706        0.579639
153    musician       638        0.523810
832     release       492        0.403941
56         live       481        0.394910
242   mastering       480        0.394089
141         ive       476        0.390805
411        band       471        0.386700
197      mixing       439        0.360427
0      recorded       406        0.333333
72     producer       396        0.325123
526       cover       386        0.316913
68         last       385        0.316092
1264    excited       379        0.311166
204       track       364        0.298851
260       money       362        0.297209
777     process       353        0.289819
968     writing       352        0.288998
626       reach       350        0.287356
31      musical       350        0.287356
12        dream       346        0.284072
18     original       345        0.283251
198      really       345        0.283251
763       heart       343        0.281609
283         put       333        0.273399
1016      going       331        0.271757
366        past       327        0.268473
199     journey       326        0.267652
522        ever       326        0.267652
49         cant       325        0.266831
231        good       321        0.263547
128        hear       319        0.261905
320        name       319        0.261905
314         fan       316        0.259442
164      guitar       313        0.256979
803    released       307        0.252053
500         lot       303        0.248768
871       raise       302        0.247947
2       already       302        0.247947
50     engineer       302        0.247947
238      little       290        0.238095
705        mean       288        0.236453
87       always       288        0.236453
1019      along       286        0.234811
270        long       283        0.232348
349     believe       280        0.229885
74        never       280        0.229885

Publishing

            word  doc_freq  doc_freq_ratio
126         book       938        0.772652
634         page       583        0.480231
75         cover       557        0.458814
723        print       520        0.428336
86        author       506        0.416804
1054        copy       472        0.388797
849         read       456        0.375618
318         word       442        0.364086
43       writing       441        0.363262
18        reader       423        0.348435
821      include       389        0.320428
218      special       382        0.314662
1296        good       377        0.310544
782       little       374        0.308072
166     printing       373        0.307249
648       backer       372        0.306425
1288     edition       372        0.306425
567      content       363        0.299012
277        reach       360        0.296540
534       writer       359        0.295717
93      shipping       358        0.294893
71        others       355        0.292422
810      created       354        0.291598
601         name       354        0.291598
285         ever       351        0.289127
712        never       350        0.288303
332         idea       350        0.288303
908     original       348        0.286656
646        order       347        0.285832
887        going       346        0.285008
1289   beautiful       345        0.284185
8           home       343        0.282537
1162     stretch       343        0.282537
37        pledge       341        0.280890
598       series       340        0.280066
377        three       340        0.280066
432         free       339        0.279242
146       medium       338        0.278418
407          ive       336        0.276771
72    publishing       335        0.275947
824      written       335        0.275947
211         hand       335        0.275947
317       always       334        0.275124
1093      future       333        0.274300
614        offer       329        0.271005
68           end       328        0.270181
1160     reading       327        0.269357
855      receive       326        0.268534
570     creating       326        0.268534
1513     journey       323        0.266063

Film & Video

                word  doc_freq  doc_freq_ratio
130         director      1024        0.509199
179            short       995        0.494779
85              crew       959        0.476877
419         producer       934        0.464446
453         festival       896        0.445549
988        character       842        0.418697
219            movie       825        0.410244
224             cast       822        0.408752
787            money       756        0.375932
345           series       750        0.372949
1284           actor       736        0.365987
856        filmmaker       733        0.364495
331           budget       731        0.363501
537         location       707        0.351566
1613        audience       696        0.346096
74            medium       649        0.322725
508             tell       648        0.322228
1511          camera       630        0.313277
1641           going       620        0.308304
314           writer       608        0.302337
1056           young       596        0.296370
827          journey       591        0.293884
812             city       590        0.293386
998         everyone       587        0.291895
291             live       584        0.290403
128         creative       579        0.287916
29              last       578        0.287419
643        equipment       577        0.286922
923             home       573        0.284933
158             past       571        0.283938
501             name       568        0.282447
565            never       567        0.281949
66         currently       565        0.280955
824              end       565        0.280955
37               big       564        0.280457
1312            ever       561        0.278966
802           screen       559        0.277971
647            award       557        0.276977
108             plan       557        0.276977
278          special       556        0.276479
1450        possible       554        0.275485
486           worked       551        0.273993
1857            role       550        0.273496
1966  postproduction       549        0.272999
280       everything       549        0.272999
527            based       549        0.272999
599            raise       548        0.272501
515            dream       546        0.271507
462           school       546        0.271507
165             good       545        0.271009

{'Technology':              word  doc_freq  doc_freq_ratio
 196       product       854        0.573539
 291      designed       802        0.538617
 66          using       746        0.501007
 71     technology       701        0.470786
 317        system       672        0.451310
 169          user       667        0.447952
 177       control       618        0.415044
 105        device       611        0.410343
 285          easy       601        0.403627
 117         power       597        0.400940
 11    development       580        0.389523
 264         build       571        0.383479
 605        better       570        0.382807
 310          tool       548        0.368032
 276        allows       539        0.361988
 296           app       533        0.357958
 392        simple       529        0.355272
 150     prototype       524        0.351914
 931         start       521        0.349899
 100         built       514        0.345198
 87          offer       509        0.341840
 648       quality       505        0.339154
 306       process       504        0.338482
 1288        ready       483        0.324379
 221       provide       483        0.324379
 496          high       483        0.324379
 341        change       480        0.322364
 141      solution       479        0.321692
 530          idea       478        0.321021
 1102      company       477        0.320349
 208         youre       476        0.319678
 666        backer       472        0.316991
 275       content       469        0.314976
 437          free       463        0.310947
 297      platform       458        0.307589
 179        access       455        0.305574
 30         future       455        0.305574
 1133       easily       449        0.301545
 345         based       448        0.300873
 408       perfect       438        0.294157
 330       created       436        0.292814
 51       possible       435        0.292142
 468      software       432        0.290128
 448       already       430        0.288784
 881      building       429        0.288113
 321        market       423        0.284083
 2053      browser       423        0.284083
 975          hand       421        0.282740
 1162      problem       421        0.282740
 159         thats       412        0.276696,
 'Games':              word  doc_freq  doc_freq_ratio
 81           game      1199        0.843179
 1101       player       864        0.607595
 285        backer       667        0.469058
 379     character       649        0.456399
 438       stretch       645        0.453586
 629           end       630        0.443038
 1190          fun       624        0.438819
 658           add       617        0.433896
 648      shipping       613        0.431083
 458        pledge       608        0.427567
 690      designed       595        0.418425
 969        system       583        0.409986
 257    additional       566        0.398031
 48          youre       562        0.395218
 234         using       558        0.392405
 510          card       557        0.391702
 995         based       538        0.378340
 562         final       533        0.374824
 2012        build       531        0.373418
 443      complete       525        0.369198
 193         start       524        0.368495
 95        playing       523        0.367792
 1721      special       519        0.364979
 1067      content       512        0.360056
 118         order       507        0.356540
 902      gameplay       507        0.356540
 53         always       502        0.353024
 359          idea       498        0.350211
 284        change       494        0.347398
 726        choose       491        0.345288
 526          book       490        0.344585
 1348         free       487        0.342475
 0         already       482        0.338959
 951      creating       480        0.337553
 340       product       479        0.336850
 441       version       477        0.335443
 1346         tier       475        0.334037
 502     adventure       473        0.332630
 755   development       472        0.331927
 587    everything       472        0.331927
 125       include       468        0.329114
 1685     everyone       467        0.328411
 795      includes       465        0.327004
 720       created       462        0.324895
 657      possible       460        0.323488
 912          last       460        0.323488
 862       digital       457        0.321378
 209           box       456        0.320675
 61           join       455        0.319972
 282      original       451        0.317159,
 'Music':            word  doc_freq  doc_freq_ratio
 309       album       895        0.734811
 92         song       880        0.722496
 268   recording       801        0.657635
 37       record       745        0.611658
 7        studio       706        0.579639
 153    musician       638        0.523810
 832     release       492        0.403941
 56         live       481        0.394910
 242   mastering       480        0.394089
 141         ive       476        0.390805
 411        band       471        0.386700
 197      mixing       439        0.360427
 0      recorded       406        0.333333
 72     producer       396        0.325123
 526       cover       386        0.316913
 68         last       385        0.316092
 1264    excited       379        0.311166
 204       track       364        0.298851
 260       money       362        0.297209
 777     process       353        0.289819
 968     writing       352        0.288998
 626       reach       350        0.287356
 31      musical       350        0.287356
 12        dream       346        0.284072
 18     original       345        0.283251
 198      really       345        0.283251
 763       heart       343        0.281609
 283         put       333        0.273399
 1016      going       331        0.271757
 366        past       327        0.268473
 199     journey       326        0.267652
 522        ever       326        0.267652
 49         cant       325        0.266831
 231        good       321        0.263547
 128        hear       319        0.261905
 320        name       319        0.261905
 314         fan       316        0.259442
 164      guitar       313        0.256979
 803    released       307        0.252053
 500         lot       303        0.248768
 871       raise       302        0.247947
 2       already       302        0.247947
 50     engineer       302        0.247947
 238      little       290        0.238095
 705        mean       288        0.236453
 87       always       288        0.236453
 1019      along       286        0.234811
 270        long       283        0.232348
 349     believe       280        0.229885
 74        never       280        0.229885,
 'Publishing':             word  doc_freq  doc_freq_ratio
 126         book       938        0.772652
 634         page       583        0.480231
 75         cover       557        0.458814
 723        print       520        0.428336
 86        author       506        0.416804
 1054        copy       472        0.388797
 849         read       456        0.375618
 318         word       442        0.364086
 43       writing       441        0.363262
 18        reader       423        0.348435
 821      include       389        0.320428
 218      special       382        0.314662
 1296        good       377        0.310544
 782       little       374        0.308072
 166     printing       373        0.307249
 648       backer       372        0.306425
 1288     edition       372        0.306425
 567      content       363        0.299012
 277        reach       360        0.296540
 534       writer       359        0.295717
 93      shipping       358        0.294893
 71        others       355        0.292422
 810      created       354        0.291598
 601         name       354        0.291598
 285         ever       351        0.289127
 712        never       350        0.288303
 332         idea       350        0.288303
 908     original       348        0.286656
 646        order       347        0.285832
 887        going       346        0.285008
 1289   beautiful       345        0.284185
 8           home       343        0.282537
 1162     stretch       343        0.282537
 37        pledge       341        0.280890
 598       series       340        0.280066
 377        three       340        0.280066
 432         free       339        0.279242
 146       medium       338        0.278418
 407          ive       336        0.276771
 72    publishing       335        0.275947
 824      written       335        0.275947
 211         hand       335        0.275947
 317       always       334        0.275124
 1093      future       333        0.274300
 614        offer       329        0.271005
 68           end       328        0.270181
 1160     reading       327        0.269357
 855      receive       326        0.268534
 570     creating       326        0.268534
 1513     journey       323        0.266063,
 'Film & Video':                 word  doc_freq  doc_freq_ratio
 130         director      1024        0.509199
 179            short       995        0.494779
 85              crew       959        0.476877
 419         producer       934        0.464446
 453         festival       896        0.445549
 988        character       842        0.418697
 219            movie       825        0.410244
 224             cast       822        0.408752
 787            money       756        0.375932
 345           series       750        0.372949
 1284           actor       736        0.365987
 856        filmmaker       733        0.364495
 331           budget       731        0.363501
 537         location       707        0.351566
 1613        audience       696        0.346096
 74            medium       649        0.322725
 508             tell       648        0.322228
 1511          camera       630        0.313277
 1641           going       620        0.308304
 314           writer       608        0.302337
 1056           young       596        0.296370
 827          journey       591        0.293884
 812             city       590        0.293386
 998         everyone       587        0.291895
 291             live       584        0.290403
 128         creative       579        0.287916
 29              last       578        0.287419
 643        equipment       577        0.286922
 923             home       573        0.284933
 158             past       571        0.283938
 501             name       568        0.282447
 565            never       567        0.281949
 66         currently       565        0.280955
 824              end       565        0.280955
 37               big       564        0.280457
 1312            ever       561        0.278966
 802           screen       559        0.277971
 647            award       557        0.276977
 108             plan       557        0.276977
 278          special       556        0.276479
 1450        possible       554        0.275485
 486           worked       551        0.273993
 1857            role       550        0.273496
 1966  postproduction       549        0.272999
 280       everything       549        0.272999
 527            based       549        0.272999
 599            raise       548        0.272501
 515            dream       546        0.271507
 462           school       546        0.271507
 165             good       545        0.271009}

In [17]:
category_stopwords_all = set()

for category_name, high_freq_words in category_high_freq_words.items():
    category_words = high_freq_words["word"].tolist()
    category_stopwords_all.update(category_words)
    print(f"\n{category_name} ({len(category_words)} words)")
    print(category_words)

print(f"\nTotal unique category stopwords: {len(category_stopwords_all)}")
category_stopwords_all

Technology (50 words)
['product', 'designed', 'using', 'technology', 'system', 'user', 'control', 'device', 'easy', 'power', 'development', 'build', 'better', 'tool', 'allows', 'app', 'simple', 'prototype', 'start', 'built', 'offer', 'quality', 'process', 'ready', 'provide', 'high', 'change', 'solution', 'idea', 'company', 'youre', 'backer', 'content', 'free', 'platform', 'access', 'future', 'easily', 'based', 'perfect', 'created', 'possible', 'software', 'already', 'building', 'market', 'browser', 'hand', 'problem', 'thats']

Games (50 words)
['game', 'player', 'backer', 'character', 'stretch', 'end', 'fun', 'add', 'shipping', 'pledge', 'designed', 'system', 'additional', 'youre', 'using', 'card', 'based', 'final', 'build', 'complete', 'start', 'playing', 'special', 'content', 'order', 'gameplay', 'always', 'idea', 'change', 'choose', 'book', 'free', 'already', 'creating', 'product', 'version', 'tier', 'adventure', 'development', 'everything', 'include', 'everyone', 'includes', 'created', 'possible', 'last', 'digital', 'box', 'join', 'original']

Music (50 words)
['album', 'song', 'recording', 'record', 'studio', 'musician', 'release', 'live', 'mastering', 'ive', 'band', 'mixing', 'recorded', 'producer', 'cover', 'last', 'excited', 'track', 'money', 'process', 'writing', 'reach', 'musical', 'dream', 'original', 'really', 'heart', 'put', 'going', 'past', 'journey', 'ever', 'cant', 'good', 'hear', 'name', 'fan', 'guitar', 'released', 'lot', 'raise', 'already', 'engineer', 'little', 'mean', 'always', 'along', 'long', 'believe', 'never']

Publishing (50 words)
['book', 'page', 'cover', 'print', 'author', 'copy', 'read', 'word', 'writing', 'reader', 'include', 'special', 'good', 'little', 'printing', 'backer', 'edition', 'content', 'reach', 'writer', 'shipping', 'others', 'created', 'name', 'ever', 'never', 'idea', 'original', 'order', 'going', 'beautiful', 'home', 'stretch', 'pledge', 'series', 'three', 'free', 'medium', 'ive', 'publishing', 'written', 'hand', 'always', 'future', 'offer', 'end', 'reading', 'receive', 'creating', 'journey']

Film & Video (50 words)
['director', 'short', 'crew', 'producer', 'festival', 'character', 'movie', 'cast', 'money', 'series', 'actor', 'filmmaker', 'budget', 'location', 'audience', 'medium', 'tell', 'camera', 'going', 'writer', 'young', 'journey', 'city', 'everyone', 'live', 'creative', 'last', 'equipment', 'home', 'past', 'name', 'never', 'currently', 'end', 'big', 'ever', 'screen', 'award', 'plan', 'special', 'possible', 'worked', 'role', 'postproduction', 'everything', 'based', 'raise', 'dream', 'school', 'good']

Total unique category stopwords: 174

{'access',
 'actor',
 'add',
 'additional',
 'adventure',
 'album',
 'allows',
 'along',
 'already',
 'always',
 'app',
 'audience',
 'author',
 'award',
 'backer',
 'band',
 'based',
 'beautiful',
 'believe',
 'better',
 'big',
 'book',
 'box',
 'browser',
 'budget',
 'build',
 'building',
 'built',
 'camera',
 'cant',
 'card',
 'cast',
 'change',
 'character',
 'choose',
 'city',
 'company',
 'complete',
 'content',
 'control',
 'copy',
 'cover',
 'created',
 'creating',
 'creative',
 'crew',
 'currently',
 'designed',
 'development',
 'device',
 'digital',
 'director',
 'dream',
 'easily',
 'easy',
 'edition',
 'end',
 'engineer',
 'equipment',
 'ever',
 'everyone',
 'everything',
 'excited',
 'fan',
 'festival',
 'filmmaker',
 'final',
 'free',
 'fun',
 'future',
 'game',
 'gameplay',
 'going',
 'good',
 'guitar',
 'hand',
 'hear',
 'heart',
 'high',
 'home',
 'idea',
 'include',
 'includes',
 'ive',
 'join',
 'journey',
 'last',
 'little',
 'live',
 'location',
 'long',
 'lot',
 'market',
 'mastering',
 'mean',
 'medium',
 'mixing',
 'money',
 'movie',
 'musical',
 'musician',
 'name',
 'never',
 'offer',
 'order',
 'original',
 'others',
 'page',
 'past',
 'perfect',
 'plan',
 'platform',
 'player',
 'playing',
 'pledge',
 'possible',
 'postproduction',
 'power',
 'print',
 'printing',
 'problem',
 'process',
 'producer',
 'product',
 'prototype',
 'provide',
 'publishing',
 'put',
 'quality',
 'raise',
 'reach',
 'read',
 'reader',
 'reading',
 'ready',
 'really',
 'receive',
 'record',
 'recorded',
 'recording',
 'release',
 'released',
 'role',
 'school',
 'screen',
 'series',
 'shipping',
 'short',
 'simple',
 'software',
 'solution',
 'song',
 'special',
 'start',
 'stretch',
 'studio',
 'system',
 'technology',
 'tell',
 'thats',
 'three',
 'tier',
 'tool',
 'track',
 'user',
 'using',
 'version',
 'word',
 'worked',
 'writer',
 'writing',
 'written',
 'young',
 'youre'}

In [18]:
vocab = vocab - category_stopwords_all
print(f"final vocabulary length: {len(vocab)}")
df["description_processed"] = df["description_processed"].apply(
    lambda doc: [word for word in doc if word in vocab]
)

final vocabulary length: 21911

In [19]:
# only at the end 
df.to_csv('Kickstarter_processed.csv')